name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Personal Repo
        run: |
          git remote add target https://lindsay-yamagishi:${{ secrets.MIRROR_TOKEN }}@github.com/lindsay-yamagishi/jyc-portal-deploy.git
          git push --force target HEAD:main