name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # ★ここを追加！勝手に別のパスワードがセットされるのを防ぎます

      - name: Push to Personal Repo
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git remote add target https://lindsay-yamagishi:${TOKEN}@github.com/lindsay-yamagishi/jyc-portal-deploy.git
          git push --force target HEAD:main