name: Mirror to Personal Repo

on:
  push:
    branches:
      - main  # ※メインブランチ名が master の場合は master に変更してください

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push to Personal Repo
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git push --force "https://${TOKEN}@github.com/lindsay-yamagishi/jyc-portal-deploy.git" HEAD:main
          //test